# pygments: true
permalink: /:year/:month/:day/:hour:minute-:title.html
title: തെരഞ്ഞെടുപ്പ് നാൾവഴി
baseurl: 
linked_posts: true
timezone: Asia/Kolkata

# Sets the default folder in Prose.io
# Sets the default metadata in Prose.io
prose:
 rooturl: "_posts"
 metadata:
   _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "timeline"
    - name: "title"
      field:
        element: "text"
        label: "Title"
    - name: "category"
      field:
        element: "text"
        label: "Category"
    - name: "link"
      field:
        element: "text"
        label: "Link"
    - name: "excerpt"
      field:
        element: "textarea"
        label: "Excerpt"
    - name: "date"
      field:
        element: "text"
        value: CURRENT_DATETIME
    - name: "published"
      field:
        element: "checkbox"
        value: "true"
      
